### ISSUE TITLE
Is it necessary to unbind when element is removed from DOM?

### ISSUE THREAD

**Issue by steve9001** [arthurgouveia/prettyCheckable#10]
In order to avoid a memory leak, is it necessary to remove prettyCheckable from an element when it is removed from the DOM? If so, how is it done?

**Comment by arthurgouveia** [comment]
Hello!

Just make sure you're using jQuery's [remove](http://api.jquery.com/remove/) or [empty](http://api.jquery.com/empty/) methods and they will not only wipe the DOM off, but also the bound events. 

But remember that you need to use these methods on the containers surrounding the actual radios/checkboxes.

Let me know if it answers your question and if it does, please close the issue.

All the best!

**Comment by steve9001** [comment]
OK. I'm using emberjs and the view is added or removed by the router changing states, so I guess I'll have to investigate somewhere else whether this would unbind.  Thanks
