### ISSUE TITLE
How to revert to checkboxes instead of Div containers..

### ISSUE THREAD

**Issue by seattlekyle** [arthurgouveia/prettyCheckable#11]
Is there anyway I can call $('#someElement').prettyCheckable().revert();

I want to revert to just the original <input > instead of the <div><input ...><a></div> before knockoutjs removes the items from the collection.

I am using an observableArray in knockout and binding it to a foreach template repeater in a div container.

You can see below in the afterRender event I make it pretty using your plugin

<div id="Counties" class="well well-large checkbox inline" data-bind="template: { name: 'CountiesTemplate', foreach: counties, beforeRemove: revertPrettyCheckable, afterRender: postRenderCountyCheckboxes }">

My function : 

postRenderCountyCheckboxes = function (elements) {
        $(elements[1]).prettyCheckable();
    };

Excerpt from my viewModel :

counties([{ name: 'King', id: '3435353252' }, { name: 'Pierce', id: '1435353252' }]);

My template :

<script type="text/html" id="CountiesTemplate">
    <input type="checkbox" data-bind="attr: { 'data-label': name, value: id }, checked: $root.countiesSelected"/>
</script>

**Comment by seattlekyle** [comment]
For now I just call $('#containerDiv").empty(); to remove all the checkbox child divs that prettycheckable creates from the parent container. I'm guessing this is probably the best solution.

**Comment by arthurgouveia** [comment]
Hey @seattlekyle! Yesterday I added a function to enable/disable checkboxes and I'm guessing I could also add one to revert the input back to the original state.

But would you mind explaining why would you need this?

**Comment by seattlekyle** [comment]
Not sure if I will yet, I'm not full time working on that project anymore,
so I will let you know if I still need it in the future sometime.

**Comment by arthurgouveia** [comment]
Thanks. Would you mind closing the issue (feature request), then?

**Comment by seattlekyle** [comment]
I will try later
