### ISSUE TITLE
jQuery .change() function and checked value

### ISSUE THREAD

**Issue by michahell** [arthurgouveia/prettyCheckable#15]
I have a table (2 columns, 20 something rows) where the first column is filled with checkboxes. i use a .change jQuery function to check the checked property on each checkbox:

```
$('input.memberPropertyCheckbox').change(function () {
    // ...
    console.log($(this).attr('value') + ": " + $(this).prop('checked'));
    // ...
}
```

This gives the following output after toggling the checkbox 4 times:

![Screen Shot 2013-02-23 at 22 41 25 PM](https://f.cloud.github.com/assets/225784/188641/2744ee8c-7e02-11e2-8a17-8c7b19d59ec3.png)

As you can see, the checked property is being set, but somehow is not the same as how the checkbox normally does this. i've verified this by not using prettyCheckable, and then i get the following output:

![Screen Shot 2013-02-23 at 22 45 19 PM](https://f.cloud.github.com/assets/225784/188645/57099f46-7e02-11e2-98ad-6c3a3730eb6c.png)

As you would expect checkboxes do when being toggled.
So something is not going right. i've checked in the document inspector, and the checked="checked" property IS being set by prettyCheckable. is this a jQuery issue, or a prettyCheckable issue?

**Comment by 3zzy** [comment]
having the same issue, and the form is not being submitted correctly in major browsers so its pretty much useless to me right now :(

**Comment by arthurgouveia** [comment]
Hello, guys.

I see you're using .change, instead of .on('change', function(){});

Would you two mind trying?

You see, here's the prettyCheckable website, with basically the same code @michahell wrote, but using .on and I get the correct values.

http://cl.ly/image/04423S0N013D

The attribute "checked" is added to the radio/checkbox, therefore the browser will submit it with the correct value.

Let me know how that works for you.

**Comment by 3zzy** [comment]
Just tried that, the browser (Firefox) still doesn't submit the correct value. :(

**Comment by arthurgouveia** [comment]
@3zzy is there a way that you can show me your code? Maybe host it somewhere online?

I don't understand how the browser would not submit the checked checkbox/radio is the attribute "checked" is being added to the selected choice.

**Comment by michahell** [comment]
Sorry guys, i was away from home for a few days. i just tried @arthurgouveia remark and, weird enough, this works! Is using that way of listening for DOM events using jQuery better in general, and does it differ from
.change() that much or should i file a possible bug over at yayQuery's? :) anyway, glad it works, looks a lot better then default checkboxes :+1:

**Comment by arthurgouveia** [comment]
@michahell thing is that .change is not a listener, but instead an action, like .click! :)

**Comment by 0xadri** [comment]
Just beeing curious: did you end up removing .change() ?
