### ISSUE TITLE
Disabled / Checked classes mixed up

### ISSUE THREAD

**Issue by amarcucci** [arthurgouveia/prettyCheckable#22]
I'm trying to create checkboxes that are initially checked and initially disabled, however, all of them appear disabled and checked (even example in prettyCheckable's main page is like that). Is there a way to handle both states and any combination of the two?

**Comment by arthurgouveia** [comment]
Sorry for the long time to get back to you. I've only added one style for the disabled checkboxes. Would you like to extend the behavior to make it possible to have it disabled and both checked and unchecked states?
