### ISSUE TITLE
Could you tag your versions?

### ISSUE THREAD

**Issue by markushausammann** [arthurgouveia/prettyCheckable#23]
Automatic installation and update of your component would be much easier, if you had version tags like 1.0.0, 1.0.1, etc. Please tag your versions!

**Comment by markushausammann** [comment]
And if you could now also make a version tag, that would be even greater, because then we can install this with composer easily.

**Comment by arthurgouveia** [comment]
https://github.com/arthurgouveia/prettyCheckable/tags

Thanks :)

**Comment by markushausammann** [comment]
Thank you!
