### ISSUE TITLE
Disabled state missing from PSD?

### ISSUE THREAD

**Issue by markushausammann** [arthurgouveia/prettyCheckable#24]
As far as I can tell, the disabled state is missing in the PSD or how is the gray disabled checkbox state achieved?

**Comment by arthurgouveia** [comment]
Yeah. I totally forgot to upload the file I've updated. I'll do it at some point, today.

**Comment by markushausammann** [comment]
Well, I already made a pull request which contains the version I made. This has all gray colours for a more design agnostic approach. I you don't want to include it, no problem.

**Comment by arthurgouveia** [comment]
Sweet. Then I would not advise you to make a pull request to overwrite the original PSD. Instead, create a new PNG file and a CSS rule for your color theme, like the ones already on the plugin, ok?

Thanks!

**Comment by markushausammann** [comment]
There is no original PSD.

**Comment by arthurgouveia** [comment]
For what I saw on the other issue, you haven't seen the plugin landing page. Check this out: http://cl.ly/image/0J1Q241w2V3K

**Comment by arthurgouveia** [comment]
@markushausammann, check this: https://github.com/arthurgouveia/prettyCheckable/commit/2e876c79c8e5e174f72dc0979a96b54f539acd6d

Sorry for taking long to upload it.
