### ISSUE TITLE
Dead link to Photoshop file

### ISSUE THREAD

**Issue by markushausammann** [arthurgouveia/prettyCheckable#25]
The link at the top of the page to the psd file is dead.

**Comment by arthurgouveia** [comment]
Hello, @markushausammann.

If you're meaning that this link "Four color options (Twitter bootstrap) + editable PSD;" is broken, something weird happened, because I've just clicked it and also the one on the very bottom and it's working.

**Comment by markushausammann** [comment]
The one at the bottom works, but the top one doesn't!

**Comment by arthurgouveia** [comment]
Both links are pointing to http://arthurgouveia.com/prettyCheckable/goodies/prettyCheckable.psd

I don't see why one would work and not the other one.

**Comment by markushausammann** [comment]
No, the first link points to https://github.com/arthurgouveia/prettyCheckable/blob/master/goodies/prettyCheckable.psd

**Comment by arthurgouveia** [comment]
Oh, I see what you're talking about.

You're talking about the README.MD from the github description, not the plugin landing page: http://arthurgouveia.com/prettyCheckable/

Thanks for noticing. I'll be fixing this today.

**Comment by markushausammann** [comment]
yep, I only use github!

**Comment by arthurgouveia** [comment]
Just commited the correct readme.md with the link.

**Comment by markushausammann** [comment]
:+1:
