### ISSUE TITLE
Add a way to programatically check or uncheck

### ISSUE THREAD

**Issue by sylvainpolletvillard** [arthurgouveia/prettyCheckable#28]
Hello,

In our application we have many prettyCheckable checkboxes which are changing state automatically in certain conditions. To programatically set the state of the checkbox, we need to set the property checked of input tag AND set the right class to prettyCheckable DOM, like this:

```
$input_wrapper.find(":checkbox").prop("checked", isChecked).end().find(".prettycheckbox a").toggleClass("checked", isChecked);
```

Could you please add a method to do these two actions ? Or maybe listen to "change" event on the input tag and set the right classes to prettyCheckbox after that.
Thanks

**Comment by arthurgouveia** [comment]
Hey, @sylvainpolletvillard!

It is on the roadmap but I'm not sure if I'll be able to do it anytime in the next two weeks. Would you like to give it a try?

Regarding the listener for change, you should add the listener manually on the input and do whatever you want with it because the input already triggers change events:

``` javascript
        if (input.prop('checked')) {

            input.prop('checked', false).change();

        } else {

            input.prop('checked', true).change();

        }
```

Thanks!

**Comment by sylvainpolletvillard** [comment]
Hi Arthur,

Here is my first try :

```
function addCheckableEvents(element){
        element
            .find('a, label').on('click', function(e){
                e.preventDefault();
                var clickedParent = $(this).closest('.clearfix');
                var input = clickedParent.find('input');
                if (input.prop('disabled') !== true) {
                    input.prop('checked', !input.prop('checked')).change();
                }
            }).on('keyup', function(e){ if (e.keyCode === 32) $(this).click(); }).end()
            .find('input').on('change', function(){
                var clickedParent = $(this).closest('.clearfix');
                var fakeCheckable = clickedParent.find('a');
                if ($(this).attr('type') == 'radio') {
                    $('input[name="' + $(this).attr('name') + '"]').each(function(index, el){
                        $(el).removeAttr('checked').parent().find('a').removeClass('checked');
                    });
                }
                fakeCheckable.toggleClass('checked', this.checked);
            });
    }
```

I think it makes more sense to set the "checked" class regarding the input change event rather than the click event. Then I just have to call : 

```
$input_wrapper.find(":checkbox").prop("checked", isChecked).change();
```

This seems to work for me, but I will recommend you to have a closer look ;)

**Comment by sylvainpolletvillard** [comment]
Second try :

```
//addCheckableEvents(el.parent());
addCheckableEvents(el);

function addCheckableEvents(element){
        var fakeCheckable = element.siblings('a');
        element.on('change', function(){
            if ($(this).attr('type') == 'radio') {
                $('input[name="' + $(this).attr('name') + '"]').prop('checked', false);
            }
            fakeCheckable.toggleClass('checked', this.checked);
        });
        fakeCheckable.on('click',  function(event){
            event.preventDefault();
            event.stopImmediatePropagation();
            $(this).closest('.clearfix').find('input').trigger('click');
        }).on('keyup', function(e){ if (e.keyCode === 32) $(this).click(); });
    }
```

I think this one is quite better as it kinda redirects the click event to the input tag, so the "disabled" behaviour should be handled natively. Need further testing, however

**Comment by arthurgouveia** [comment]
@sylvainpolletvillard maybe you should try cloning the gh-pages repo, updating your code and running the tests. If everything is good as expected, you should do a pull request so that we can work together improving the plugin. What do you think?

**Comment by arthurgouveia** [comment]
BTW, if you haven't seen the plugin landing page, it's arthurgouveia.com/prettyCheckable and you can run the tests by clicking on the top right link on the page.

**Comment by sylvainpolletvillard** [comment]
I would be glad to help, but I'm not used to git and github. But I'll try to find some time for this.

**Comment by arthurgouveia** [comment]
No problem! Let me know if I can be of any help :)
