### ISSUE TITLE
500 error when trying to download zip of tag

### ISSUE THREAD

**Issue by markushausammann** [arthurgouveia/prettyCheckable#30]
I don't know if that has something to do with how you made the tag or if something is wrong on the github side. When trying to open the zip of tag v1.0 I get a 500 error.

**Comment by arthurgouveia** [comment]
Not sure. I've done the usual procedures. Might be a problem with GH itself.

**Comment by markushausammann** [comment]
It was a file server maintenance or something.

**Comment by tamlyn** [comment]
I'm getting this too when trying to download any project, both in Chrome and in Composer.

![image](https://f.cloud.github.com/assets/115310/558020/0446822a-c406-11e2-9437-350ca0fd0290.png)

![image](https://f.cloud.github.com/assets/115310/558023/31faa7d2-c406-11e2-829b-8b025ef208fe.png)

Edit: now it works. It was broken for at least several minutes.

**Comment by markushausammann** [comment]
That happens when github's file server is down.
