### ISSUE TITLE
Checkmarks not showing when clicking on text

### ISSUE THREAD

**Issue by markushausammann** [arthurgouveia/prettyCheckable#32]
Hey @arthurgouveia, have you seen the case that the state of the control is actually changed by clicking on the label (as it should) but the checkmarks are not shown? It happens to me at the moment and I don't know if it's a CSS interaction or some JS interaction. I'd be happy to hear you know about the problem...

**Comment by markushausammann** [comment]
When I look at the examples on your page and click the labels, I see that there is a class 'checked' which is added and removed in the a element. On my page, this doesn't happen. I guess that is connected with the problem.

**Comment by arthurgouveia** [comment]
Markus, can you make sure you're using jQuery 1.9.1 and the latest version of the plugin?

**Comment by markushausammann** [comment]
That is the case. I know realized that when I add my lable as data-label, it works but then I have two labels. I want this to work including gracefull degradation, meaning if I switch prettyCheckable off, everything should still work.

**Comment by arthurgouveia** [comment]
Feel free to make a pull request and I'll check it.
