### ISSUE TITLE
How to validate?

### ISSUE THREAD

**Issue by johnhorner** [arthurgouveia/prettyCheckable#33]
I've used PrettyCheckable to style some checkboxes. I want to validate them client side but I can't see how it would even work: looking at the HTML PrettyCheckable wraps the checkbox in a DIV and puts a graphic over the top in an `a` element, and toggles a "checked" class on the `a` -- without passing the click on to the hidden checkbox. 

So when the form is submitted, the checkbox isn't actually checked? Does it check them on the submit event?

**Comment by arthurgouveia** [comment]
Hello, @johnhorner. The plugin does a .prop('checked', boolean).

Open [the code](https://github.com/arthurgouveia/prettyCheckable/blob/master/prettyCheckable.js) and look for "prop('checked"
