### ISSUE TITLE
checkbox deselect

### ISSUE THREAD

**Issue by manuele89** [arthurgouveia/prettyCheckable#37]
I need that when a checkbox is deselected (for example id "test1") is unchecked another checkbox (for example id "test").

I've tried some methods (all working for a normal checkbox) but there aren't working for checkbox with prettyCheckable class.

Can I do this operations?

Thank You

**Comment by arthurgouveia** [comment]
Hello, @manuele89. Would you be so kind and give me a URL where I can see your code?

Basically, the plugin has a trigger for change events and you need to add listeners for the checkboxes you need specific actions for.

You can check a checkable input using the methods listed on the documentation or by triggering a click action on the label or anchor tags inside the plugin wrapper.

Let me know if you need further assistance!

**Comment by arthurgouveia** [comment]
https://github.com/arthurgouveia/prettyCheckable#methods
