### ISSUE TITLE
Knockout compatibility

### ISSUE THREAD

**Issue by angelpcadena** [arthurgouveia/prettyCheckable#38]
Make prettyCheckable compatible with knockout bindings

Fiddle: http://jsfiddle.net/WV69n/1/

**Comment by angelpcadena** [comment]
I added partial support for knockout bindings, removeAll() still doesn't work

Fiddle: http://jsfiddle.net/WV69n/2/ (Test in firefox, chrome doesn't like linking code from raw.github.com)

**Comment by Jorgelig** [comment]
Added: https://github.com/arthurgouveia/prettyCheckable/pull/41

**Comment by arthurgouveia** [comment]
I believe this was done by @Jorgelig and merged on d6ea83e3fce654e0ee3f5b83550fa36d044bccba
