### ISSUE TITLE
Something goes wrong calling the plugin after an ajax call

### ISSUE THREAD

**Issue by matteopoile** [arthurgouveia/prettyCheckable#4]
I initialize the plugin like this:
$('.checkable input').prettyCheckable();
and everything goes well.
Then i make an ajax call that insert into a container div with id="tool-results" some input inside others divs with class="checkable" and I initialize that inputs with $('#tool-results .checkable input').prettyCheckable();
The checkbox inside the new divs with class="checkable" work correctly but the older checkbox don't, it seem that the new call to prettyCheckable ($('#tool-results .checkable input').prettyCheckable()) damage the inputs not inside div #tool-results, it seems some events sum to other events attached previously.
If I click on the old checkbox the click will be triggered twice.

I also tried to call the plugin twice on $(document).ready()

$('.checkable input').prettyCheckable();
$('.checkable input').prettyCheckable();

 without making any ajax call and someone went wrong anyway, checkables don't work correctly anymore, it seems some events sum to other events attached previously.
Maybe this can help you to spot the problem.

**Comment by arthurgouveia** [comment]
I'll investigate this, but in the meantime, I'd like to know if when you are initialising prettyCheckable again, are you using the a selector that could probably target the already initialised custom checkboxes?

I'll try to reproduce the error here, but maybe try initialising prettyCheckable on the new inputs with a more specific query so that it doesn't run on the customised ones.

**Comment by matteopoile** [comment]
Hi Arthur, thanks a lot for your early reply.
I'm not sure I understand what you are suggesting but I'm already using a more specific query after the ajax calls:
- On document ready when the page load first I need every checkbox replaced so I use a generic:
  $('.checkable input').prettyCheckable();
  My input type radio and checkbox are always wrappend in a <div class="checkable"></div>
- After the ajax call I try to target only the new inserted <div class="checkable"></div>  with:
  $('#tool-results .checkable input').prettyCheckable();
  Despite of this, the old checkbox have the problems I tried to explain in my previous post, it seems like the "context" is missing and the plugin is reattached to all the $('.checkable input') in the page.

I'm doubtful on line 30:

28    function loadCheckBoxEvents(){
29
30      $('div.prettycheckbox a, div.prettyradio a, div.prettycheckbox label, div.prettyradio label').on('touchstart click', function(e){

Is the "context" missing on line 30? 
After my ajax call how does the plugin Know to attach the click event only to $('#tool-results .checkable input')?

I hope my english is understandable :)

**Comment by arthurgouveia** [comment]
Got it.

It is attaching the event listener X times to the prettyCheckbox DOM, X being the amount of times you initialised the plugin.

I'm looking into the solution as we speak.

**Comment by matteopoile** [comment]
Great!
Waiting to try new code ;)

**Comment by arthurgouveia** [comment]
Heads up: I'll be offline for a while. The code **should** be up by tonight!

**Comment by matteopoile** [comment]
Perfect!

**Comment by arthurgouveia** [comment]
Let me know if that solves your problem. 

BTW, loved the interface.

I'm thinking about starting a session on the plugin page with a showcase of people using prettyCheckable. May I have your link listed?

Also, how did you feel implementing, customizing and using the plugin? Was it easy and intuitive?

**Comment by matteopoile** [comment]
I'll try the code tomorrow :).
No problem for the showcase but not now please, the link posted is a demo area, i will give you the correct URL after deploying the site in production.
I like very much your plugin, I'll think about other improvements.

**Comment by matteopoile** [comment]
It works!!!
