### ISSUE TITLE
KO compatibility update has broken "checked" property

### ISSUE THREAD

**Issue by xpopov** [arthurgouveia/prettyCheckable#42]
Hi,

Input - checkbox's property "checked" never change, if I click the control.

Please check this post: http://stackoverflow.com/questions/16950688/how-to-validate-forms-which-use-the-prettycheckable-jquery-plugin/16950912#16950912

That guy says it works, BUT! He uses an old version of prettyCheckable in his fiddle: http://jsfiddle.net/hescano/SSWJu/1/

WIth new version of prettyCheckable
this code:
$(".prettycheckbox").on("click",function(){
        alert($(this).find("input[type='checkbox']").prop("checked"));
});
always alerts "false".

**Comment by arthurgouveia** [comment]
You should listen to 'change' events on the inputs.

The plugin triggers a change event for the hidden inputs once the label or the a are clicked.

What version of jQuery are you using? Can you create a jsFiddle or codepen.io?

**Comment by arthurgouveia** [comment]
I just updated the JavaScript since I found a bug that was breaking the plugin. Please update your version and also jQuery's to at least 1.9

Thanks.

**Comment by arthurgouveia** [comment]
@xpopov is this still an issue?

Anyway, I just pushed a new version of prettyCheckable, which was basically re-written.
Please check the documentation again and do the changes you need.

Let me know if it solves the issue and please close it.

Thanks!

https://github.com/arthurgouveia/prettyCheckable
