### ISSUE TITLE
Cannot save modified checkbox

### ISSUE THREAD

**Issue by gbonline** [arthurgouveia/prettyCheckable#43]
hi, on my app i'm trying to use your prettyCheckable on a form with a variable number of checkboxes, so the checkboxes are grouped on a array when they are created from the rails script, so every checkbox get the name as  " estimate[opts][...] " where ... is corrected with the correspondant db id. 
On submit i get a array opts[] in the validate and save script. When i create the form on page it will be possible that some checkboxes are prechecked. 
till now all goes well: unselected and preselected checkboxes are rendered correctly.
the trouble was on the save script: in the opts array i could not have the new checkboxes i set on form, only the presetted !! After spending some hour to check my script, i've found a solution on your prettyCheckble.js:

i've simply swapped the content on rows 96 and 100
and now i have 

```
     input.click();

      if (input.prop('checked')) {

          input.prop('checked', true).change();

      } else {

          input.prop('checked', false).change();

      }
```

and my script get the corrected checked checkboxes.
Giorgio

**Comment by arthurgouveia** [comment]
Hello. I just noticed this input.click(); line. It was not necessary and in fact, was breaking the plugin.

Please update your version to the latest and let me know if it still works.

**Comment by gbonline** [comment]
Hi, thank's for the update: the checkboxes are saved correctly.
Giorgio
