### ISSUE TITLE
maybe it is useful to have images inside css

### ISSUE THREAD

**Issue by diegodorado** [arthurgouveia/prettyCheckable#46]
i've done it with the help of compass...it is useful since you dont need to uploads images, and you dont have to follow a fixed path pattern for your assets

i'm new collaborating to projects...if you find useful to provide an alternate stylesheet, how may i send it to you?

**Comment by arthurgouveia** [comment]
What do you mean you did with the help of compass? You've encoded it to base64?

If that's the case, prettyCheckable still supports old browsers, like IE7~IE8 and they have limitations regarding the support to Data URI imagery.

If you want to make tests with the currently supported browsers, I'll gladly merge your pull request.

As for collaborating, see if this helps: https://help.github.com/articles/using-pull-requests

**Comment by arthurgouveia** [comment]
@diegodorado I'll be closing this issue since I explained the lack of compatibility with legacy browsers, ok?

Maybe it will come in a few years when I drop support for those.
