### ISSUE TITLE
prettyCheckable breaks the "required" property, at least in Chrome

### ISSUE THREAD

**Issue by mholt** [arthurgouveia/prettyCheckable#48]
For example, I have two radio buttons named "gender" on my form. They both have the "required" property. When I try to submit the form, Chrome gives me this error in the inspector:

`An invalid form control with name='gender' is not focusable.`

Obviously, since the original elements are hidden, Chrome can't focus on them to make you fill them out. Is there a work-around for this?

**Comment by arthurgouveia** [comment]
I see your point. I'll try to look into it, but I have no clue where to start.

**Comment by mholt** [comment]
I'm not sure how this would work, either. The hidden element would have to lose the "required" attribute, but you'd have to enforce it some other way. I'm still redesigning my site and I'll let you know if I discover any little tricks.

**Comment by arthurgouveia** [comment]
Much appreciated, @mholt. Thanks for the help!

**Comment by arthurgouveia** [comment]
@mholt I haven't had any success solving this and I believe so far you too.

Should we close this?

**Comment by mholt** [comment]
I'm enforcing those required fields manually in the meantime. We can close this if you want.

**Comment by arthurgouveia** [comment]
I'll tag it as enhancement but I'll still not sure how we could do this.

I'm planning on replacing the imagery for CSS3 stuff if I can successfully remove the looks of the input:checkbox/radio. This would remove the need for an anchor tag to play the role of input, solving your issue.

**Comment by Gussarah** [comment]
I added this styles for input:radio in block to work correctly

 height: 0;
    opacity: 0.0000001;
    width: 1px;
    display: list-item;
