### ISSUE TITLE
Not Keyboard Accessible in Firefox

### ISSUE THREAD

**Issue by TalD** [arthurgouveia/prettyCheckable#5]
I'm trying to use prettyCheckable in Firefox (16.0.2 on Mac).
Tabbing, enter, and spacebar do not work as they do in Chrome.

**Comment by arthurgouveia** [comment]
I'm investigating this issue, but it seems that Firefox & Safari are not allowing focus while tabbing, on anchor tags. I'll try to come up with something.

**Comment by arthurgouveia** [comment]
Since you're on a Mac, check this, please: http://support.mozilla.org/pt-BR/kb/Pressing%20Tab%20key%20does%20not%20select%20menus%20or%20buttons

Anyway, it focuses, but when you hit Tab it bugs. I'll check it out.

**Comment by TalD** [comment]
As a temporary fix I did the following:
1. Wrapped the input in a div (giving that div a class name)
2. Assigned that div a tabindex
3. Used jQuery to listen for keyup on enter or spacebar on that div
4. Triggered a click event on the anchor that is rendering / toggling the checkbox on keyup

**Comment by arthurgouveia** [comment]
Make sure you have Safari & Firefox enabled to focus elements with Tabs. You must set it manually.

Please let me know if it works for you.
