### ISSUE TITLE
An example of check/uncheck single/all would be cool

### ISSUE THREAD

**Issue by demiro** [arthurgouveia/prettyCheckable#50]
I have a scenario where I have to uncheck all checkboxes... regardless of their previous state... an example of how to do that would be great..
- you should add two methods .... check / uncheck... (regardles of the prev. state)

**Comment by arthurgouveia** [comment]
@demiro check the latest version. Should be fairly simple now.

**Comment by arthurgouveia** [comment]
Make a loop, either using a .each or a for, and for each element, call $(yourElement).prettyCheckable('check') or 'uncheck'.
