### ISSUE TITLE
How to track the change / click event on radio button?

### ISSUE THREAD

**Issue by echteinfachtv** [arthurgouveia/prettyCheckable#51]
Maybe stupid me? I cannot find the information in the readme.

I am having two radio buttons: 
`<input id="uc_1" checked />`
`<input id="uc_2"/>`

Then I prettify them: 
`$('input').prettyCheckable();`

Now I need to change other stuff, as soon as the checkbox uc_1 or uc_2 is clicked. 

I tried `data-bind="checked:myfunction"` within the input but it did not work.

Thanks for letting me know the basics :-)

**Comment by arthurgouveia** [comment]
First, make sure you have the same name attribute for the radio, otherwise it won't realize it's the same option you're referring to.

Now, just add a .on('change') jQuery listener to the input you want, check if it is checked and do what you need :)

**Comment by echteinfachtv** [comment]
Thx for the lightning fast answer :)

Above I forgot to note down the names: 
`<input id="uc_1" name="myopt[]" type="radio" checked />`
`<input id="uc_2" name="myopt[]" type="radio" />`

`$("#uc_1").click( function() { ... } );` does not work as prettyCheckable has set its own elements over the checkboxes.
So how do I track the onclick / onchange?

**Comment by echteinfachtv** [comment]
`$("#uc_1").on('change', function() {...});` did the trick, thanks a lot for your help and the tool provided!
