### ISSUE TITLE
Prettycheckable is breaking my form [data not being sent]

### ISSUE THREAD

**Issue by Zaay** [arthurgouveia/prettyCheckable#52]
Hello!

I have a checkboxes and radios which I am stayling with prettycheckable.
Now, when prettycheckable is enabled NONE of my forms is sending data from checked checkboxes on submit. If i disable prettycheckable data is correct.

**Comment by arthurgouveia** [comment]
Do you have a live URL? What's the jQuery version you're using?

**Comment by Zaay** [comment]
Sorry I cannot provide live url as I am still in development mode (developing in Ruby on Rails)  -->. I am using jQuery version:
jQuery JavaScript Library v1.8.2

Evertthing is working, just if checkbox is checked data is not being sent with from.

**Comment by arthurgouveia** [comment]
Update it to at least 1.9. Should work.

**Comment by Zaay** [comment]
1.9 didn't worked, I updated to latest version and started working. THANK YOU!

**Comment by Zaay** [comment]
Hm, now another strange error.. After updating jQuery to 1.10.2, all of my prettyCheckboxes are loading properly, but none of my click events on them is working. If i disable prettycheckboxes my logic for click events is working. 

```
$('input[type="checkbox"]').prettyCheckable();

/// Home page latest comments filter system
$("input[name='show-filter-home']").click(function() {

    $(".elem").fadeOut();

});
```

My code is working if I dont initialize prettyCheckable. Why my click events won't work ?

**Comment by arthurgouveia** [comment]
Not sure. Might be a problem with the .clone method I'm using to replicate
your checkboxes.

Try adding a .on('change') listener do the particular checkbox you want.
Check if it is :checked and do your action.

Might work.

## 

Arthur Gouveia
arthurgouveia.com

**Comment by arthurgouveia** [comment]
@Zaay, any progress?

**Comment by arthurgouveia** [comment]
I just pushed a new version of prettyCheckable, which was basically re-written.
Please check the documentation again and do the changes you need.

Let me know if it solves the issue and please close it.

Thanks!

https://github.com/arthurgouveia/prettyCheckable

**Comment by patatoid** [comment]
any updates ?
