### ISSUE TITLE
Bug: Checkboxes do not change visual state at .prop("checked", false)

### ISSUE THREAD

**Issue by markushausammann** [arthurgouveia/prettyCheckable#53]
When a prettycheckable checkbox is unchecked programmatically, it does not show this, the check stays.

**Comment by arthurgouveia** [comment]
You mean when you select the hidden input field and set .prop('checked', true/false)?

**Comment by markushausammann** [comment]
yes.

**Comment by milantrax** [comment]
You can add this: prop('checked', false).next('a').removeClass('checked')

**Comment by arthurgouveia** [comment]
Yeah... I'm going to add a check/uncheck method, as well as the disabled method with and without the check on the image. This should do the trick.

**Comment by arthurgouveia** [comment]
@markushausammann, boy, you're gonna like my next release :)

Your so desired fallback will finally come to life :+1:

**Comment by markushausammann** [comment]
Sounds great :-) :+1:

**Comment by arthurgouveia** [comment]
- Sass + Compass written + smart sprite generation;
- Enable/Disable methods added;
- Check/Uncheck methods added;
- Destroy method added.

**Comment by markushausammann** [comment]
Wow, that's really great. Also the SASS/Compass integration!

**Comment by arthurgouveia** [comment]
Hello, guys.

I just pushed a new version of prettyCheckable, which was basically re-written.
Please check the documentation again and do the changes you need.

Let me know if it solves the issue and please close it.

Thanks!

https://github.com/arthurgouveia/prettyCheckable

**Comment by arthurgouveia** [comment]
@markushausammann is this issue closed? Sorry I couldn't reply to the other ones. I'm in a huge rush :)

**Comment by markushausammann** [comment]
I don't know yet, the project where this was an issue will be updated after the base framework and I can't update the baseframework as long as you don't merge my pull request in the other ticket. :)

**Comment by arthurgouveia** [comment]
About that, I'm still analysing.

I want to make sure that the plugin is easy enough to implement and is not
DOM structure dependant, that's why I'm only using the input and all the
rest is generated with params.

I'll let you know more once I get more time to work on it!

Thanks.

**Comment by markushausammann** [comment]
Sure, as I wrote, the original implementation is left completely intact, with the additional option to make it degradable.

**Comment by elijahpaul** [comment]
Can't seem to implement the Check/Uncheck method correctly. Here [fiddle](http://jsfiddle.net/2GYHk/3/). Any advice?

**Comment by arthurgouveia** [comment]
@elijahpaul here's the fiddle: http://jsfiddle.net/2GYHk/7/

I updated the prettyCheckable version and called .prettyCheckable on each of your inputs, as the documentation states, instead of calling the plugin on a jQuery result.

Please use the check/uncheck methods.

**Comment by elijahpaul** [comment]
@arthurgouveia Bit late, but thanks. Works great.
