### ISSUE TITLE
Firefox and IE problem

### ISSUE THREAD

**Issue by DavidSMS** [arthurgouveia/prettyCheckable#54]
http://www.electionsportal.ge/geo/map <-- I use your code but it's not worked on firefox and IE. please help

**Comment by arthurgouveia** [comment]
You should use CSS Sprites. You're using one image for standard look and one image for checked look. Seems the Firefox is having problems re-rendering the new background image. Try the sprite and let me know.

**Comment by DavidSMS** [comment]
sorry it was my problem :)

i missed  a.checked:focus{ background-position: -35px 0px; } --> was 0px 0px
