### ISSUE TITLE
How to call enableInput/disaableInput ?

### ISSUE THREAD

**Issue by demiro** [arthurgouveia/prettyCheckable#55]
So, you are offering two methods, but there is no example of how actually call this methods...

I tried like:
jQuery('#checkbox').prettyCheckable("disableInput");

and
jQuery('#checkbox').prettyCheckable().disableInput();

not working

**Comment by arthurgouveia** [comment]
Store the prettyCheckable return on a var, look for your element on the array and call the method.

**Comment by arthurgouveia** [comment]
@demiro 

I just pushed a new version of prettyCheckable, which was basically re-written.
Please check the documentation again and do the changes you need.

Let me know if it solves the issue and please close it.

Thanks!

https://github.com/arthurgouveia/prettyCheckable

**Comment by arthurgouveia** [comment]
I'm closing this issue as now we have available 'enable' and 'disable' methods. Thanks.
