### ISSUE TITLE
Check boxes behaving as radio boxes

### ISSUE THREAD

**Issue by demiro** [arthurgouveia/prettyCheckable#56]
My client has a particular request...

in one occasion they want check boxes to behave as radio boxes (that means that only one can be checked with the same name)...

what would be the best way to achieve this?

**Comment by arthurgouveia** [comment]
If what your client really wants is indeed radio inputs, just change the
position of the radio inputs for the checkboxes on the sprite.

You'll have radios with the looks of checkboxes.

**Comment by arthurgouveia** [comment]
@demiro ?

**Comment by demiro** [comment]
Hey!

no, sadly they want actual radio boxes (behaving as radio boxes) with the appearance of the check boxes...
your suggestion would work, if everywhere else the behavior would not be default...(meaning whole app uses the boxes as intended, except in one occasion)  :|

**Comment by arthurgouveia** [comment]
@demiro I believe you worked it out. It's mainly a matter of switching the background-position of your checkboxes/radios.
