### ISSUE TITLE
set checkbox checked by jquery

### ISSUE THREAD

**Issue by sivaswamy88** [arthurgouveia/prettyCheckable#57]
its setting in normal checkbox but in prettycheckable it not showing the checked value

**Comment by arthurgouveia** [comment]
What version of jQuery are you using? I've seen jQuery behave in different ways when using the .prop function. When the form is submitted it sets the input as checked, but visually it is nor, nor the "checked" attribute is added to it.

You need jQuery 1.9, at least.

**Comment by NunoBentes** [comment]
I´m having the same issue!!!! prettyCheckable it´s not syncronizing with my real input wit the attribute checked/uncheck. Have you got any idea how can we solve this situation?

**Comment by arthurgouveia** [comment]
Hello, guys.

I just pushed a new version of prettyCheckable, which was basically re-written.
Please check the documentation again and do the changes you need.

Let me know if it solves the issue and please close it.

Thanks!

https://github.com/arthurgouveia/prettyCheckable

**Comment by arthurgouveia** [comment]
I'm closing this issue. If you use the 'check' or 'uncheck' method, this should be solved.

**Comment by pr0fess0r** [comment]
This seems to work for me. Essentially you have to find the tag parent that is created by prettyCheckable around your checkbox and set that as well as the input:

$("#element").prop("checked", true).parent().find("a:first").addClass("checked");
