### ISSUE TITLE
Add id to div element

### ISSUE THREAD

**Issue by marcusamargi** [arthurgouveia/prettyCheckable#60]
Thanks for creating this plugin :-)

It would be useful to be able to access the injected div by id.

line 139 of prettyCheckable.js could be something like this:

```
el.wrap('<div id="' + this.element[0].id + '-wrapper" class="clearfix ' + containerClasses + '"></div>').parent().html();
```

**Comment by arthurgouveia** [comment]
@pymarco this would mean that the input itself would lose it's ID attribute or it would generate a duplicate ID on the DOM.

Anyway, what's your use for this? If you have an ID on your input, you can access the wrapping div by $('#myInput').parent()

**Comment by marcusamargi** [comment]
Thanks for the .parent() tip. That is what I will do. The use case is that I need to trigger a click event for the checkbox.

However, no duplicate id would be necessary. In the line of code that I included I append "-wrapper" to the element's id creating a distinct id for the div.

**Comment by arthurgouveia** [comment]
So, should we close it?
