### ISSUE TITLE
Default Radio Button On Page load

### ISSUE THREAD

**Issue by SamirTripathy** [arthurgouveia/prettyCheckable#63]
Hello friends,

I ahve 3 radio buttons.How can it be possible to make one of them is to be selected at page load through Knockout JS.
Check it in below link.

http://jsfiddle.net/samir_tripathy73/Zzx3D/

**Comment by arthurgouveia** [comment]
Add the attribute "checked" on one of them.

**Comment by SamirTripathy** [comment]
Thanks for replay,

i know how to do that, through HTML.
But i need this functionality in knockout.
i tried a lot in KO but i am failed.

**Comment by arthurgouveia** [comment]
Adding the checked atrribute makes the plugin check the radio/checkbox by
default.

Isn't that what you need? The KnockOut integration was not done by me so
I'm not sure I'll be able to dig in the code that was added and figure out
your problem.

**Comment by SamirTripathy** [comment]
Thanks, Actually my requirement is in KO.Not through the HTML , CSS or any simple JQuery. I think i have to struggle a bit more.
Thanks.
