### ISSUE TITLE
Multiple different data-label values; first data-label value gets used for all created labels

### ISSUE THREAD

**Issue by MK-Chris** [arthurgouveia/prettyCheckable#65]
Hi there

I am probably doing something completely stupid, as it seems this issue hasn't come up before...!  I appear to have an issue whereby the data-label value from my first checkbox gets used on all checkboxes, regardless of their own data-label values, like in the below JSFiddle:

http://jsfiddle.net/MKChris/5y2Uz/

I'd appreciate if someone would be able to point me in the right direction?

Many thanks.

Chris

**Comment by arthurgouveia** [comment]
Hey, Chris!

You need to make a loop with all your inputs and call prettyCheckable on
each one individually.

Check documentation: there's an example there ;)

**Comment by MK-Chris** [comment]
Oh, brilliant, thank you - I thought I had read it, clearly not properly....!

Thanks again.
