### ISSUE TITLE
With multiple checkboxes on a single form, all checkboxes have the label of first checkbox

### ISSUE THREAD

**Issue by Qadeer786** [arthurgouveia/prettyCheckable#67]
Hi,
I have the following markup in a boostrap-3 framework. The checkboxes show up correctly, but the data-label property does not have any effect on the checkboxes.

```
......
<div class="form-group">
<input type="checkbox" name="discover-clusters" id="discover-clusters" class="form-control prettyCheckable uitip" data-label="Find clusters." />
<input type="checkbox" name="discover-linkapps" id="discover-linkapps" class="form-control prettyCheckable uitip" data-label="Link applications." />    
</div>
........
```

On inspecting using Inspect tool... the id for the label tag is not picking the updated values when element changes.. it keeps using the id that was used for first element. Below is the markup for checkbox with id discover-linkapps, however the label tag shows for attribute as "discovery-clusters"

```
<div class="clearfix prettycheckbox labelright  blue">
  <input id="discover-frs" class="prettyCheckable uitip" type="checkbox" data-label="Link applications" name="discover-linkapps" style="display: none;">  </input>
  <a class=" " href="#"></a>
  <label for="discover-clusters"></label>
</div>
```

In the above notice that <label for=""> has discover-clusters which is that of the earlier element. The actual value should have been discover-linkapps.

**Comment by arthurgouveia** [comment]
Can you show me how you're initialising the plugin?
