### ISSUE TITLE
If selector does not find any elements initialization crashes

### ISSUE THREAD

**Issue by lahma** [arthurgouveia/prettyCheckable#68]
We have issues on dynamically created pages where input might be present or not.

Code:

$('.not-found-for-some-reason').prettyCheckable();

Result:

TypeError: Cannot set property 'element' of undefined

Cause:

prettyCheckable tries to set plugin using this.data() which fails as selector yielded zero results.

**Comment by arthurgouveia** [comment]
Got the problem. But how about, for now, include the plugin initialisation only if you do have inputs you'd like to change the look?

**Comment by lahma** [comment]
Yes I'm using jQuery.each as a workaround:

$('.might-not-exist').each(function(key, elem) { $(elem).prettyCheckable(); });
