### ISSUE TITLE
Onchange order of events

### ISSUE THREAD

**Issue by bitxl** [arthurgouveia/prettyCheckable#69]
When I have an onchange attribute on my input (e.g. a function that does an ajax request) I find that that onchange is executed before the change of the checkbox/radio. Is there an option or hack to run the UI update before the onchange events?

**Comment by arthurgouveia** [comment]
I'd suggest you to drop the intrusive approach of using onchange attribute and adding an event listener on the input itself.

**Comment by bitxl** [comment]
I had already tried

```
$("input[onchange='recalc();']").each(function(){
        $(this).on('change', recalc).removeAttr('onchange');
});
```

on document ready, which afterwards is still functional, but does the same... The ajax event in this function first is executed before the UI change...

**Comment by arthurgouveia** [comment]
Remove the onChange attributes and select the input with another query.

``` javascript
$(".recalcInputs").each(function(){
        $(this).on('change', recalc());
});
```

Should to the trick.

**Comment by bitxl** [comment]
Ok that didn't work either... Started looking at the dist code and saw that

```
f.toggleClass("checked")
```

is executed after the 

```
e.prop("checked") ? e.prop("checked", !1).change() : e.prop("checked", !0).change()
```

I swapped them and now it works as I wanted to, even with the onchange attributes :)

In your dev code it's putting line 93 before line 75, bugfix perhaps?
