### ISSUE TITLE
Change anchor to button

### ISSUE THREAD

**Issue by GabiAxel** [arthurgouveia/prettyCheckable#7]
Anchor with href="#" may not be suitable for JavaScript applications that use the hash for client-side navigation. Changing it to a button (and adding border:none in the CSS) resolves this.

**Comment by arthurgouveia** [comment]
Hello, @GabiAxel! Thanks for the suggestion.

Have you actually had any problems with this? There's an event.preventDefault() when the anchor tags are clicked so it does not add the "#" on the URL or trigger default actions.

Can you share your experience with more details?

**Comment by GabiAxel** [comment]
Hi.

When I used the library as is with Firefox, clicking the anchor did cause a browser redirect from /myurl#something to myurl/#

I replaced all "a" with "button" in the JS and CSS, and added "border:none" to the button's style, and it solved the problem. However button doesn't seem to support the focus pseudo selector, so I couldn't set the focused images. I used the focused images with the active pseudo selector instead, it's good enough for me.

A possible alternative that worked when I tried it is to keep the anchor, and replace href="#" with href="javascript:void(0)", but I'm not sure if it's considered a good practice.

**Comment by arthurgouveia** [comment]
Is the URL of what you're trying to do public? I could not reproduce this behaviour on the landing page for the plugin:
http://screencast.com/t/AT4gJ3Udt

I added a #something to the end of the page, reloaded and accessed it using this URL and no matter what I do, it does not change the URL. Maybe is something else from your scripts that is listening and changing the URL, no?

Debug the action from prettyCheckable. Let it complete the action once it is clicked and see if there are any changes to your app's url. I believe is a listener for anchor tags from another script of yours.

**Comment by GabiAxel** [comment]
Indeed I couldn't reproduce it on the demo page, so probably something else on my application causes this behavior. Thanks and keep up the good work.

**Comment by arthurgouveia** [comment]
Much welcome. Thanks for the feedback.
