### ISSUE TITLE
Input checked Attribute

### ISSUE THREAD

**Issue by chapterjason** [arthurgouveia/prettyCheckable#70]
The Detection for is Checked fail!!

**Comment by fseminario** [comment]
I think I am having the same issue. All radio buttons and checkboxes are showing up unselected even with the "checked" attributed passed. Working once one clicks though.

JS

```
$(document).ready(function () {
    $('.prettyC').prettyCheckable({});
 });
```

HTML

```
<form name="myform" action="http://www.mydomain.com/myformhandler.cgi" method="POST">
<div align="center"><br>
<input type="radio" name="group1" value="Milk" class="prettyC"> Milk<br>
<input type="radio" name="group1" value="Butter" checked class="prettyC"> Butter<br>
<input type="radio" name="group1" value="Cheese"> Cheese
<hr>
<input type="radio" name="group2" value="Water"> Water<br>
<input type="radio" name="group2" value="Beer"> Beer<br>
<input type="radio" name="group2" value="Wine" checked> Wine<br>
</div>
</form>
```

**Comment by arthurgouveia** [comment]
How's the detection not working, @MrBubbleSquare ?
Can you give me more details?

@fseminario you need to call .prettyCheckable for each input. Make a query to select everything you need and inside a loop, iterate through it and call the init method on each one. Check documentation for details.

**Comment by fseminario** [comment]
i only called for the first two to check and since one had a checked value, expected it to work.

I just tried adding it to all of them and same thing...

Updated HTML

```
<form name="myform" action="http://www.mydomain.com/myformhandler.cgi" method="POST">
        <div align="center"><br>
        <input type="radio" name="group1" value="Milk" class="prettyC"> Milk<br>
        <input type="radio" name="group1" value="Butter" checked class="prettyC"> Butter<br>
        <input type="radio" name="group1" value="Cheese" class="prettyC"> Cheese
        <hr>
        <input type="radio" name="group2" value="Water" class="prettyC"> Water<br>
        <input type="radio" name="group2" value="Beer" class="prettyC"> Beer<br>
        <input type="radio" name="group2" value="Wine" checked class="prettyC"> Wine<br>
        </div>
        </form>
```

![alpha originpc com _frameworks html5 boilerplate initializr classic index html](https://f.cloud.github.com/assets/4037582/2398801/1768d432-a9f9-11e3-8999-c5abf4164f08.png)

**Comment by arthurgouveia** [comment]
Please use JSFiddle or Codepen with the code so that I can try to help.

**Comment by fseminario** [comment]
http://jsfiddle.net/fseminario/kZHJW/2/

**Comment by arthurgouveia** [comment]
Dude, you need to read what I said to help you :)

"
@fseminario you need to call .prettyCheckable for each input. Make a query to select everything you need and inside a loop, iterate through it and call the init method on each one. Check documentation for details.
"

http://jsfiddle.net/kZHJW/3/

**Comment by fseminario** [comment]
thanks. i guess i dont know javascript as well as i thought. Im just starting to learn it.

**Comment by fseminario** [comment]
why not have that in the "start the plugin" instructions instead of what is there now?

**Comment by arthurgouveia** [comment]
https://github.com/arthurgouveia/prettyCheckable#install--setup

Everything's pretty much written in there. For a single input or multiple.

**Comment by fseminario** [comment]
i guess what i meant to say was right now you have this:

```
$().ready(function(){

  $('input.myClass').prettyCheckable({
    color: 'red'
  });

});
```

which does not work with checked by itself. if you showed:

```
$().ready(function(){

$('input.myClass').each(function() {
 $(this).prettyCheckable({
 color: 'red'
 });
});

});
```

wouldn't it always work?

**Comment by arthurgouveia** [comment]
If you only have **one** input you want to customize, then the first option will do the job and it's more optimized.

If you have **more than one** input, you need to select all of them and init the plugin on each one.

There's no point in using an .each loop if you only have **one** input.

**Comment by fseminario** [comment]
ok makes sense.just thought this might happen often since multiple radios are used more often than one. donated a beer. thanks

**Comment by arthurgouveia** [comment]
Much appreciated :+1:

**Comment by chapterjason** [comment]
Srry im new registered on Github and online with web proxy some functions didnt work like delete :S here is want i ment

``` html
<div class="clearfix prettycheckbox labelleft blue">

    <input type="checkbox" data-label="Spalten Layout ?" name="col" title="Spalten Layout ?" data-labelposition="left" style="display: none;"></input>
    <label for="undefined">

        Spalten Layout ?

    </label>
    <a class="checked" href="#"></a>

</div>
```

it should be like this

``` html
<div class="clearfix prettycheckbox labelleft blue">

    <input type="checkbox" data-label="Spalten Layout ?" name="col" title="Spalten Layout ?" data-labelposition="left" style="display: none;" checked="checked"></input>
    <label for="undefined">

        Spalten Layout ?

    </label>
    <a class="checked" href="#"></a>

</div>
```

**Comment by arthurgouveia** [comment]
I still can't understand.

Please use a JSFiddle or Codepen.

**Comment by chapterjason** [comment]
Here the URL http://codepen.io/anon/pen/rphzm
I ment the Input Tag "without" the attribute checked="checked" after change the state with clicking.
Here an Image: http://www.img-host.de/bild.php/47178,unbenannt3IHGBX.png

**Comment by arthurgouveia** [comment]
Does not mean it is not checked.

http://codepen.io/anon/pen/LHbDA

**Comment by chapterjason** [comment]
About this i find nothing in the Documentation Nice!
