### ISSUE TITLE
Checkbox is hidden and sprites not loading.

### ISSUE THREAD

**Issue by EminenceHC** [arthurgouveia/prettyCheckable#71]
Well the checkbox works, but is completely hidden. I don't think the sprites are loading. I am using sprockets, not grunt. What can I check that may be causing the checkbox to not show up entirely?

**Comment by arthurgouveia** [comment]
Can you show me some code?

Try JSFiddle or Codepen.
Have you inspected the element to see if the sprites are accessible directly or if the images are not being found?
