### ISSUE TITLE
data-label Not working

### ISSUE THREAD

**Issue by bharatlovecss** [arthurgouveia/prettyCheckable#73]
I had a problem with data-label. It doesn't work and it show
label for="undefined"

My Code
input type="checkbox" class="pretyCheck" data-label="b&amp;c danflock" checked

**Comment by arthurgouveia** [comment]
Can you paste the link for the page you're using this?

Or maybe a JSFiddle/Codepen

**Comment by bharatlovecss** [comment]
OK I have attach jsfiddle link: http://jsfiddle.net/K8M2W/2/ 
But in jsfiddle at least the data label are shown but the first one data-label repeated. But in my localhost there is no data label text. I don't know what's wrong with or have I missed something ?

Ok I have attach my localhost screenshot:  
![2014-03-14_1654](https://f.cloud.github.com/assets/1442211/2420185/bd703f14-ab6b-11e3-8c49-2e74b54f9006.png)

**Comment by arthurgouveia** [comment]
As the documentation states, you need to call .prettyCheckable on each input.

http://jsfiddle.net/K8M2W/3/

As for the labels not showing up on your localhost, my guess is that your CSS if overwriting prettyCheckable's CSS selectors.

**Comment by arthurgouveia** [comment]
As for the for="undefined" on your labels, it happens because you attach a label to an input by an id atribute.

Your inputs do not have any ID, and therefore, they get the undefined value.

**Comment by bharatlovecss** [comment]
It works :) thank you.
