### ISSUE TITLE
bootstrap checkboxes

### ISSUE THREAD

**Issue by reddo** [arthurgouveia/prettyCheckable#74]
If used with bootstrap checkbox markup:

``` html
<label class="checkbox"><input type="checkbox" name="p1">Label here</label>
```

I get:

``` html
<label class="checkbox has-pretty-child"><div class="clearfix prettycheckbox labelright  blue"><input type="checkbox" name="p1" style="display: none;"><a href="#" class=" "></a>
<label for="undefined"></label></div>Label here</label>
```

As you can see, duplicate labels (one of them empty) and also the padding from the bootstrap checkbox causes an empty padding before each checkbox.

**Comment by arthurgouveia** [comment]
Hello, @reddo.

You need to use the data-label syntax. Don't use the DOM as you wrote.

As for the Twitter Bootstrap CSS, you simply check what is overwriting the selectors from prettyCheckable and adjust.

**Comment by reddo** [comment]
I see... Any way to disable automatic empty labels and just to leave the original labels as they were?

**Comment by arthurgouveia** [comment]
Not ATM. Sorry.
