### ISSUE TITLE
No blue shadow on focus in Chrome

### ISSUE THREAD

**Issue by vkryzhov** [arthurgouveia/prettyCheckable#82]
Chrome ver. 35.0.1916.153 m

**Comment by arthurgouveia** [comment]
You'll need to be more specific and provide better details.

If you're talking about the :focus state, it is provided by the sprite.
I'm also using Chrome 35.0.1916.153.

**Comment by vkryzhov** [comment]
I'm sorry.
Yes. I'm talking about :focus state.
In my Chrome no :focus state for both checkbox and radio button.

For example on your page http://arthurgouveia.com/prettyCheckable/ in
Firefox anchore node <a href="#" class="checked"></a> has style
.prettycheckbox a.checked:focus {
   background-position: -90px 0;
}

But in Chrome :focus is absent
.prettycheckbox a.checked {
  background-position: -60px 0;
}

2014-07-03 16:11 GMT+03:00 Arthur Gouveia notifications@github.com:

**Comment by arthurgouveia** [comment]
This screenshot is from Chrome: https://www.dropbox.com/s/jzydd2l44m0w1lk/Screenshot%202014-07-03%2010.32.13.png
