### ISSUE TITLE
Multiple data-label doesn't work properly

### ISSUE THREAD

**Issue by benjauger** [arthurgouveia/prettyCheckable#98]
If we have some checkbox with different "data-label" inside a loop (php, engine tpl ...), prettyCheckable doesn't work and does not appear distinct diffrents "data-label" ...

For example :
(in bold : data-label, in small : realy data)
<img src="http://tuk.fr/s/241014042340.png" />

**Comment by tarampampam** [comment]
I'v got this bug too. Fuck this shit.

**Comment by benjauger** [comment]
I've changed this by another framework ... Waiting for a fix.

**Comment by arthurgouveia** [comment]
Please provide a sample of how you guys are instantiating the plugin.

**Comment by rphilipsenbas** [comment]
http://pastebin.com/Yhp1SUb4

Tested on Windows with Chrome 39 and Firefox 34.

**Comment by arthurgouveia** [comment]
Yeah. Read the doc. You're initializing it wrong.

**Comment by tarampampam** [comment]
@BloodMotion use this - http://fronteed.com/iCheck/ - thats great

**Comment by benjauger** [comment]
@tarampampam It's done ;-) The same choice !
